# Generated by Django 5.2 on 2025-04-21 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('bio', models.TextField(blank=True, help_text='About You....')),
                ('location', models.CharField(max_length=100)),
                ('theme', models.CharField(choices=[('Theme-1', '1')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Give your project a name...', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('link', models.URLField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/PingMeUp/projects/')),
                ('created_at', models.DateField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='PingMeUp.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Give your skill a name (ex:Baking)', max_length=100)),
                ('about', models.CharField(help_text='Would you care to elaborate?', max_length=300)),
                ('level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermidiate', 'Intermidiate'), ('Expert', 'Expert'), ('Was born for this', 'Was born for this')], max_length=100)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='PingMeUp.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('FaceBook', 'FaceBook'), ('Instagram', 'Instagram'), ('GitHub', 'GitHub')], max_length=100)),
                ('url', models.URLField(help_text='Enter link to platform...')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='PingMeUp.profile')),
            ],
        ),
    ]
